Traceback (most recent call last):
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/remi/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import plt_util
  
pch1 = pd.read_csv('../source_data/params_ch1.csv')
pch4 = pd.read_csv('../source_data/params_ch4.csv')

plt_util.py_params(pch1, 'Ch1', dict(l=100,r=100,b=40,t=40,pad=0))
plt_util.py_params(pch4, 'Ch4', dict(l=100,r=100,b=0,t=40,pad=0))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_842430/3494672855.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0mpch4[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_csv[0m[0;34m([0m[0;34m'../source_data/params_ch4.csv'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;34m[0m[0m
[0;32m----> 7[0;31m [0mplt_util[0m[0;34m.[0m[0mpy_params[0m[0;34m([0m[0mpch1[0m[0;34m,[0m [0;34m'Ch1'[0m[0;34m,[0m [0mdict[0m[0;34m([0m[0ml[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m[0mr[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m[0mb[0m[0;34m=[0m[0;36m40[0m[0;34m,[0m[0mt[0m[0;34m=[0m[0;36m40[0m[0;34m,[0m[0mpad[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0mplt_util[0m[0;34m.[0m[0mpy_params[0m[0;34m([0m[0mpch4[0m[0;34m,[0m [0;34m'Ch4'[0m[0;34m,[0m [0mdict[0m[0;34m([0m[0ml[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m[0mr[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m[0mb[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m[0mt[0m[0;34m=[0m[0;36m40[0m[0;34m,[0m[0mpad[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Workspace/gdbp_study/docs/plt_util.py[0m in [0;36mpy_params[0;34m(p, title, margin)[0m
[1;32m     73[0m                     template='plotly_white')
[1;32m     74[0m   [0;31m# fig.update_xaxes(title_text="freq. (GHz)")[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 75[0;31m   [0mfig[0m[0;34m.[0m[0mlayout[0m[0;34m.[0m[0mxaxis5[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0mtitle[0m[0;34m=[0m[0;34m"freq. (GHz)"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     76[0m   [0;31m# single axis-label trick, https://plot.ly/~empet/14983[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     77[0m   [0mfig[0m[0;34m.[0m[0mlayout[0m[0;34m.[0m[0myaxis3[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0mtitle[0m[0;34m=[0m[0;34m'amplitude (a.u.)'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Applications/miniconda3/envs/jbook/lib/python3.8/site-packages/plotly/basedatatypes.py[0m in [0;36m__getattr__[0;34m(self, prop)[0m
[1;32m   5783[0m             [0;32mreturn[0m [0mvalidator[0m[0;34m.[0m[0mpresent[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_compound_props[0m[0;34m[[0m[0mprop[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5784[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5785[0;31m             [0;32mreturn[0m [0msuper[0m[0;34m([0m[0mBaseLayoutHierarchyType[0m[0;34m,[0m [0mself[0m[0;34m)[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mprop[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5786[0m [0;34m[0m[0m
[1;32m   5787[0m     [0;32mdef[0m [0m__getitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mprop[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'Layout' object has no attribute 'xaxis5'
AttributeError: 'Layout' object has no attribute 'xaxis5'

